---
title: "brownalytics"
output: html_document
date: "2024-06-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown


```{r}
server <- function(input, output, session) {
  
  observeEvent(input$toggleInputs, {
    toggle("inputFields")
    output$attendance_plot <- renderPlot(NULL)  # Clear any existing plot
  })
  
  observeEvent(input$togglePlotInputs, {
    toggle("plotFields")
    output$attendance_plot <- renderPlot(NULL)  # Clear any existing plot
  })
  
  observeEvent(input$toggleTotalAttendanceInputs, {
    toggle("totalAttendanceFields")
  })
  
  observeEvent(input$toggleComparisonPlotInputs, {
    toggle("comparisonPlotFields")
    output$attendance_plot <- renderPlot(NULL)  # Clear any existing plot
  })
  
  observeEvent(input$toggleDaysOfWeekInputs, {
    toggle("daysOfWeekFields")
    output$attendance_plot <- renderPlot(NULL)  # Clear any existing plot
  })
  
  observeEvent(input$toggleAvgAttendanceInputs, {
    toggle("avgAttendanceFields")
  })
} 
  
  #Team and Date algorithm
  
  observeEvent(input$submit, {
    req(input$year, input$month, input$day, input$team)
    
    final_data <- tryCatch({
      get_attendance_data(input$year, input$month, input$day, input$team)
    }, error = function(e) {
      output$json_output <- renderText({
        toJSON(list(status = "error", message = e$message), pretty = TRUE)
      })
      return(NULL)
    })
    
    if (!is.null(final_data)) {
      output$json_output <- renderText({
        toJSON(final_data, pretty = TRUE)
      })
      hide("inputFields")
    }
  })
  
  
  #Scatter Plot Event
  
  observeEvent(input$generatePlot, {
    req(input$plot_year, input$plot_month, input$plot_day)
    
    tryCatch({
      plot_data <- get_attendance_data_all_teams(input$plot_year, input$plot_month, input$plot_day)
      
      all_team_logos <- data.frame(
        HomeTeam = c(
          "Orioles", "Red Sox", "Yankees", "Blue Jays", "Rays",
          "White Sox", "Guardians", "Tigers", "Royals", "Twins",
          "Astros", "Angels", "Athletics", "Mariners", "Rangers",
          "Braves", "Marlins", "Mets", "Phillies", "Nationals",
          "Cubs", "Reds", "Brewers", "Pirates", "Cardinals",
          "Diamondbacks", "Rockies", "Dodgers", "Padres", "Giants"
        ),
        Logo = c(
          "https://www.mlbstatic.com/team-logos/110.svg",
          "https://www.mlbstatic.com/team-logos/111.svg",
          "https://www.mlbstatic.com/team-logos/147.svg",
          "https://www.mlbstatic.com/team-logos/141.svg",
          "https://www.mlbstatic.com/team-logos/139.svg",
          "https://www.mlbstatic.com/team-logos/145.svg",
          "https://www.mlbstatic.com/team-logos/114.svg",
          "https://www.mlbstatic.com/team-logos/116.svg",
          "https://www.mlbstatic.com/team-logos/118.svg",
          "https://www.mlbstatic.com/team-logos/142.svg",
          "https://www.mlbstatic.com/team-logos/117.svg",
          "https://www.mlbstatic.com/team-logos/108.svg",
          "https://www.mlbstatic.com/team-logos/133.svg",
          "https://www.mlbstatic.com/team-logos/136.svg",
          "https://www.mlbstatic.com/team-logos/140.svg",
          "https://www.mlbstatic.com/team-logos/144.svg",
          "https://www.mlbstatic.com/team-logos/146.svg",
          "https://www.mlbstatic.com/team-logos/121.svg",
          "https://www.mlbstatic.com/team-logos/143.svg",
          "https://www.mlbstatic.com/team-logos/120.svg",
          "https://www.mlbstatic.com/team-logos/112.svg",
          "https://www.mlbstatic.com/team-logos/113.svg",
          "https://www.mlbstatic.com/team-logos/158.svg",
          "https://www.mlbstatic.com/team-logos/134.svg",
          "https://www.mlbstatic.com/team-logos/138.svg",
          "https://www.mlbstatic.com/team-logos/109.svg",
          "https://www.mlbstatic.com/team-logos/115.svg",
          "https://www.mlbstatic.com/team-logos/119.svg",
          "https://www.mlbstatic.com/team-logos/135.svg",
          "https://www.mlbstatic.com/team-logos/137.svg"
        )
      )
      
      plot_data <- merge(plot_data, all_team_logos, by = "HomeTeam", all.x = TRUE)
      plot_data <- na.omit(plot_data)
      
      output$attendance_plot <- renderPlot({
        ggplot(plot_data, aes(x = HomeTeam, y = AttendancePercentage)) +
          geom_point(size = .1) +
          geom_hline(yintercept = mean(plot_data$AttendancePercentage, na.rm = TRUE), color = "red", linetype = "dashed") +
          scale_y_continuous(limits = c(0, 100), breaks = seq(0, 100, by = 10), labels = scales::comma) +
          labs(
            title = paste("Attendance Capacity Percentage for Home Teams on", paste(input$plot_year, input$plot_month, input$plot_day, sep = "-")),
            x = "Home Team",
            y = "Attendance Percentage"
          ) +
          theme_minimal() +
          theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
          geom_image(aes(image = Logo), size = 0.09)  # Adjust image size and position as needed
      })
    }, error = function(e) {
      output$attendance_plot <- renderPlot(NULL)
      showNotification("Failed to fetch data. Please check your inputs.", type = "error")
    })
  })
  
  
  #Total attendance Event 
  
  observeEvent(input$getTotalAttendance, {
    req(input$total_year, input$total_team, input$num_games)
    
    total_attendance <- get_total_attendance_through_games(
      year = input$total_year, 
      team = input$total_team, 
      num_games = input$num_games
    )
    
    result <- list(
      Year = input$total_year,
      Team = input$total_team,
      Number_of_Games = input$num_games,
      Total_Attendance = total_attendance
    )
    
    result_json <- toJSON(result, pretty = TRUE)
    
    output$json_output <- renderText({
      result_json
    })
  })
  
  
  
  #Comparison Plot event
  
  observeEvent(input$generateComparisonPlot, {
    req(input$comparison_year, input$comparison_team1, input$comparison_team2, input$comparison_team3, input$comparison_team4, input$comparison_team5)
    
    tryCatch({
      print("Starting comparison plot generation")
      
      season_data_team1 <- get_season_attendance(input$comparison_year, input$comparison_team1, api_key)
      season_data_team2 <- get_season_attendance(input$comparison_year, input$comparison_team2, api_key)
      season_data_team3 <- get_season_attendance(input$comparison_year, input$comparison_team3, api_key)
      season_data_team4 <- get_season_attendance(input$comparison_year, input$comparison_team4, api_key)
      season_data_team5 <- get_season_attendance(input$comparison_year, input$comparison_team5, api_key)
      
      season_data <- bind_rows(season_data_team1, season_data_team2, season_data_team3, season_data_team4, season_data_team5)
      
      season_data$team <- factor(season_data$team, levels = c(input$comparison_team1, input$comparison_team2, input$comparison_team3, input$comparison_team4, input$comparison_team5))
      
      print("Season data ready for plotting")
      
      
      output$attendance_plot <- renderPlot({
        ggplot(season_data, aes(x = date, y = cumulative_attendance, color = team)) +
          geom_line(size = 1) +
          labs(
            title = paste("Cumulative Attendance Comparison in the", input$comparison_year, "Season"),
            x = "Date",
            y = "Cumulative Attendance",
            color = "Team"
          ) +
          theme_minimal()
      })
      
      print("Comparison plot generation completed successfully")
      
    }, error = function(e) {
      output$attendance_plot <- renderPlot(NULL)
      showNotification("Failed to fetch data or generate plot. Due to 429. Run again.", type = "error")
      print("Error occurred during comparison plot generation")
      print(e)
    })
  })
  
  #Attendance by day Event
  observeEvent(input$getDaysAttendance, {
    req(input$days_year, input$days_team)
    
    tryCatch({
      attendance_by_day <- get_attendance_by_days(input$days_year, input$days_team)
      
      output$json_output <- renderText({
        toJSON(attendance_by_day, pretty = TRUE)
      })
      
      output$attendance_plot <- renderPlot({
        ggplot(attendance_by_day, aes(x = day_of_week, y = total_attendance)) +
          geom_bar(stat = "identity", fill = "steelblue") +
          labs(
            title = paste("Total Attendance by Day of the Week for", input$days_team, "in", input$days_year),
            x = "Day of the Week",
            y = "Total Attendance"
          ) +
          theme_minimal()
      })
      
    }, error = function(e) {
      output$json_output <- renderText({
        toJSON(list(status = "error", message = e$message), pretty = TRUE)
      })
      showNotification("Failed to fetch data. Please check your inputs.", type = "error")
    })
  })
  
  
 
  
#Avergae Attendance Event 
  # Toggle visibility of the "Get Average Attendance" input fields
  observeEvent(input$toggleAvgAttendanceInputs, {
    print("Toggle Average Attendance button clicked")  # Debugging print statement
    toggle("avgAttendanceFields")
  })
  
  # Calculate average attendance and display JSON
  observeEvent(input$getAvgAttendance, {
    print("Get Average Attendance button clicked")  # Debugging print statement
    
    req(input$avg_year, input$avg_team, input$avg_num_games)
    
    tryCatch({
      avg_attendance <- get_avg_attendance_through_home_games(
        year = input$avg_year, 
        team = input$avg_team, 
        num_games = input$avg_num_games
      )
      
      result <- list(
        Year = input$avg_year,
        Team = input$avg_team,
        Number_of_Home_Games = input$avg_num_games,
        Average_Attendance = avg_attendance
      )
      
      result_json <- toJSON(result, pretty = TRUE)
      
      output$json_output <- renderText({
        result_json
      })
      
      print("Average Attendance calculated successfully")  # Debugging print statement
      
    }, error = function(e) {
      output$json_output <- renderText({
        toJSON(list(status = "error", message = e$message), pretty = TRUE)
      })
      showNotification("Failed to calculate average attendance. Please check your inputs.", type = "error")
    })
  })
  
```


```{r}
library(openxlsx)
library(sqldf)
library(glue)
library(tidyverse)
library(broom)
library(gt)
library(webshot)

```


```{r}
passer_data_pfr = read.csv('https://raw.githubusercontent.com/brownalytics/qb_stats/master/pfr_passer_stats.csv')

passer_data_fo = read.csv('https://raw.githubusercontent.com/brownalytics/qb_stats/master/fo_passer_stats.csv')

passer_data_nflscrapr = read.csv('https://raw.githubusercontent.com/brownalytics/qb_stats/master/nflscrapr_passer_stats.csv')

passer_data_airyards = read.csv('https://raw.githubusercontent.com/brownalytics/qb_stats/master/cpoe_airyards.csv')
```





```{r}
today_dt = format(Sys.Date(), format = '%Y%m%d')

#### declare or source necessary functions ####

fncModelSummary_Univariate <- function(model = model){
  
  ## Purpose: Extract model name, p-value and R-square from univariate models and append them to dataframe
  ##          'model_summary' in the .GlobalEnv for comparison
  
  require(broom)
  require(tidyverse)
  
  model_name = deparse(substitute(model))
  model_ivar = tidy(model)$term[2]
  model_pval = round(as.numeric(format(glance(model)$p.value, scientific = FALSE)),9)
  model_r2 = round(glance(model)$adj.r.squared,4)
  
  if(exists('model_summary', envir = .GlobalEnv)==TRUE){
    get('model_summary', envir = .GlobalEnv)
    
    tmp_summary = tibble(model_name, model_ivar, model_pval, model_r2)
    
    model_summary <<- rbind(model_summary, tmp_summary)
    
  }else{
    
    model_summary <<-  tibble(model_name, model_ivar, model_pval, model_r2)
    
  } ## closing bracket: if(exists('model_summary', envir = .GlobalEnv)==TRUE)
  
} ## closing bracket: fncModelParams

#### wrangle pfr data ####

passer_data = passer_data_pfr
```


```{r}
passer_data <- passer_data %>% 
  mutate(adj_ppr = (td + first_downs)/att
         ,ns_fd = first_downs-td
         ,ns_fd_pg = ns_fd/g
         ,ns_fd_pa = ns_fd/att
         ,td_int_ratio = td/int) %>% 
  filter(szn < 2019) %>% 
  mutate(td_int_ratio = ifelse(td_int_ratio == 'Inf', NA, td_int_ratio))



#### split data into train/test sets ####
set.seed(65)

#### analyze pfr correlations to win_pct ####

lm_cmp_pct = lm(data = passer_data
                ,win_pct ~ cmp_pct
                ,method = 'qr')
summary(lm_cmp_pct)


lm_ns_fd = lm(data = passer_data
              ,win_pct ~ ns_fd
              ,method = 'qr')
summary(lm_ns_fd)

lm_ns_fd_pg = lm(data = passer_data
                 ,win_pct ~ ns_fd_pg
                 ,method = 'qr')
summary(lm_ns_fd_pg)

lm_ns_fd_pa = lm(data = passer_data
                 ,win_pct ~ ns_fd_pa
                 ,method = 'qr')
summary(lm_ns_fd_pa)

lm_pass_yds = lm(data = passer_data
                 ,win_pct ~ pass_yds
                 ,method = 'qr')
summary(lm_pass_yds)


lm_td = lm(data = passer_data
           ,win_pct ~ td
           ,method = 'qr')
summary(lm_td)

lm_td_pct = lm(data = passer_data
               ,win_pct ~ td_pct
               ,method = 'qr')
summary(lm_td_pct)


lm_td_pg = lm(data = passer_data
              ,win_pct ~ td_pg
              ,method = 'qr')
summary(lm_td_pg)

lm_td_pc = lm(data = passer_data
              ,win_pct ~ td_pc
              ,method = 'qr')
summary(lm_td_pc)


lm_int = lm(data = passer_data
            ,win_pct ~ int
            ,method = 'qr')
summary(lm_int)

lm_int_pct = lm(data = passer_data
                ,win_pct ~ int_pct
                ,method = 'qr')
summary(lm_int_pct)

lm_int_pg = lm(data = passer_data
               ,win_pct ~ int_pg
               ,method = 'qr')
summary(lm_int_pg)

lm_int_pinc = lm(data = passer_data
                 ,win_pct ~ int_pinc
                 ,method = 'qr')
summary(lm_int_pinc)

lm_td_int_ratio = lm(data = passer_data
                     ,win_pct ~ td_int_ratio
                     ,method = 'qr')
summary(lm_td_int_ratio)


lm_first_downs = lm(data = passer_data
                    ,win_pct ~ first_downs
                    ,method = 'qr')
summary(lm_first_downs)

lm_fd_pg = lm(data = passer_data
              ,win_pct ~ fd_pg
              ,method = 'qr')
summary(lm_fd_pg)

lm_fd_pa = lm(data = passer_data
              ,win_pct ~ fd_pa
              ,method = 'qr')
summary(lm_fd_pa)

lm_ypa = lm(data = passer_data
            ,win_pct ~ ypa
            ,method = 'qr')
summary(lm_ypa)

lm_adj_ypa = lm(data = passer_data
                ,win_pct ~ adj_ypa
                ,method = 'qr')
summary(lm_adj_ypa)

lm_ypc = lm(data = passer_data
            ,win_pct ~ ypc
            ,method = 'qr')
summary(lm_ypc)

lm_ypg = lm(data = passer_data
            ,win_pct ~ ypg
            ,method = 'qr')
summary(lm_ypg)

lm_passer_rating = lm(data = passer_data
                      ,win_pct ~ rate
                      ,method = 'qr')
summary(lm_passer_rating)

lm_qbr = lm(data = passer_data
            ,win_pct ~ qbr
            ,method = 'qr')
summary(lm_qbr)

lm_sk = lm(data = passer_data
           ,win_pct ~ sk
           ,method = 'qr')
summary(lm_sk)

lm_sack_yds = lm(data = passer_data
                 ,win_pct ~ sack_yds
                 ,method = 'qr')
summary(lm_sack_yds)

lm_net_ypa = lm(data = passer_data
                ,win_pct ~ net_ypa
                ,method = 'qr')
summary(lm_net_ypa)

lm_adj_net_ypa = lm(data = passer_data
                    ,win_pct ~ adj_net_ypa
                    ,method = 'qr')
summary(lm_adj_net_ypa)

lm_sack_pct = lm(data = passer_data
                 ,win_pct ~ sack_pct
                 ,method = 'qr')
summary(lm_sack_pct)

lm_adj_ppr = lm(data = passer_data
                ,win_pct ~ adj_ppr
                ,method = 'qr')
summary(lm_adj_ppr)

models = c('lm_adj_net_ypa', 'lm_adj_ypa', 'lm_cmp_pct', 'lm_fd_pa', 'lm_fd_pg', 'lm_adj_ppr', 'lm_first_downs', 'lm_int'
           ,'lm_int_pct', 'lm_int_pg', 'lm_int_pinc', 'lm_net_ypa', 'lm_pass_yds', 'lm_qbr', 'lm_passer_rating', 'lm_sack_pct'
           ,'lm_sack_yds', 'lm_sk', 'lm_td', 'lm_td_pc', 'lm_td_pg', 'lm_ypa', 'lm_ypc')

# fncModelSummary_Univariate(model = lm_adj_net_ypa)
# fncModelSummary_Univariate(model = lm_adj_ypa)
fncModelSummary_Univariate(model = lm_cmp_pct)
# fncModelSummary_Univariate(model = lm_fd_pa)
# fncModelSummary_Univariate(model = lm_fd_pg)
# fncModelSummary_Univariate(model = lm_adj_ppr)
# fncModelSummary_Univariate(model = lm_first_downs)
fncModelSummary_Univariate(model = lm_int)
fncModelSummary_Univariate(model = lm_int_pct)
fncModelSummary_Univariate(model = lm_int_pg)
fncModelSummary_Univariate(model = lm_int_pinc)
# fncModelSummary_Univariate(model = lm_net_ypa)
fncModelSummary_Univariate(model = lm_pass_yds)
fncModelSummary_Univariate(model = lm_sack_pct)
fncModelSummary_Univariate(model = lm_sack_yds)
fncModelSummary_Univariate(model = lm_sk)
fncModelSummary_Univariate(model = lm_td)
fncModelSummary_Univariate(model = lm_td_pc)
fncModelSummary_Univariate(model = lm_td_pg)
fncModelSummary_Univariate(model = lm_ypa)
fncModelSummary_Univariate(model = lm_ypc)
fncModelSummary_Univariate(model = lm_td_int_ratio)
fncModelSummary_Univariate(model = lm_ns_fd)
fncModelSummary_Univariate(model = lm_ns_fd_pg)
fncModelSummary_Univariate(model = lm_ns_fd_pa)


univariate_models_smy = model_summary %>% 
  arrange(model_pval, desc(model_r2))

rm(model_summary)
```

```{r}
univariate_stability_smy = univariate_models_smy %>% 
  mutate(model_ivar = gsub("ly_", "", model_ivar)) %>% 
  rename('yoy_stab_model_pval' = 'model_pval'
         ,'yoy_stab_model_r2' = 'model_r2') %>% 
  filter(!(model_ivar %in% c('qbr', 'adj_ppr', 'first_downs', 'fd_pa', 'fd_pg', 'net_ypa'
                             ,'adj_net_ypa', 'adj_ypa')))

mean_model_r2 = mean(univariate_models_smy$model_r2)
mean_yoy_model_r2 = mean(univariate_stability_smy$yoy_stab_model_r2)

## filter out any variables that are not individual stats (adj_ppr, qbr, first_downs (include td's)) ##
combined_univariate_models = univariate_models_smy %>% 
  left_join(univariate_stability_smy %>% select(model_ivar, yoy_stab_model_pval,yoy_stab_model_r2)
            ,by = 'model_ivar')

combined_model_comp = univariate_models_smy %>% 
  left_join(univariate_stability_smy %>% select(model_ivar, yoy_stab_model_pval,yoy_stab_model_r2)
            ,by = 'model_ivar') %>% 
  filter(model_ivar != 'qbr') %>% 
  filter(model_pval < 0.0001 & yoy_stab_model_pval < 0.0001 ) %>% 
  filter(yoy_stab_model_r2 >= mean_yoy_model_r2)




lm_qb_win_pct = lm(data = passer_data
                   ,win_pct ~ td + td_pg + pass_yds + ns_fd + cmp_pct +
                     ns_fd_pg + sack_pct
                   ,method = 'qr')
summary(lm_qb_win_pct)


cor1 <- passer_data %>% 
  select(win_pct,td , td_pg , pass_yds , ns_fd , cmp_pct , ns_fd_pg , sack_pct) %>% 
  cor() 

View(cor1)




lm_qb_win_pct = lm(data = passer_data
                   ,win_pct ~ td + td_pg + pass_yds + cmp_pct +
                     ns_fd_pg + sack_pct
                   ,method = 'qr')
summary(lm_qb_win_pct)


cor2 <- passer_data %>% 
  select(win_pct,td , td_pg , pass_yds , cmp_pct , ns_fd_pg , sack_pct) %>% 
  cor() 

View(cor2)

# cor2: r = .92 b/t pass_yds and td; dropped pass_yds 

#### Model iteration #3: ####

lm_qb_win_pct = lm(data = passer_data
                   ,win_pct ~ td + td_pg + cmp_pct + ns_fd_pg + sack_pct
                   ,method = 'qr')
summary(lm_qb_win_pct)

# Call:
#   lm(formula = win_pct ~ td + td_pg + cmp_pct + ns_fd_pg + sack_pct, 
#      data = passer_data, method = "qr")
# 
# Residuals:
#   Min       1Q   Median       3Q      Max 
# -0.50871 -0.12464 -0.00376  0.11972  0.63776 
# 
# Coefficients:
#   Estimate Std. Error t value Pr(>|t|)    
# (Intercept) -0.108720   0.117223  -0.927    0.354    
# td           0.011477   0.001758   6.527 1.53e-10 ***
#   td_pg        0.006942   0.033614   0.207    0.836    
# cmp_pct      1.191024   0.210582   5.656 2.50e-08 ***
#   ns_fd_pg    -0.026056   0.005501  -4.736 2.78e-06 ***
#   sack_pct    -1.808955   0.369757  -4.892 1.31e-06 ***
#   ---
#   Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
# 
# Residual standard error: 0.1819 on 547 degrees of freedom
# Multiple R-squared:  0.3834,	Adjusted R-squared:  0.3777 
# F-statistic: 68.01 on 5 and 547 DF,  p-value: < 2.2e-16

## treat collinearity

cor3 <- passer_data %>% 
  select(win_pct,td , td_pg , cmp_pct , ns_fd_pg , sack_pct) %>% 
  cor() 

View(cor3)

# cor3: r = .90 b/t td_pg and td; dropped td_pg 

#### Model iteration #4: ####

lm_qb_win_pct = lm(data = passer_data
                   ,win_pct ~ td + cmp_pct + ns_fd_pg + sack_pct
                   ,method = 'qr')
summary(lm_qb_win_pct)

# Call:
#   lm(formula = win_pct ~ td + cmp_pct + ns_fd_pg + sack_pct, data = passer_data, 
#      method = "qr")
# 
# Residuals:
#   Min       1Q   Median       3Q      Max 
# -0.51091 -0.12360 -0.00351  0.11902  0.64067 
# 
# Coefficients:
#   Estimate Std. Error t value Pr(>|t|)    
# (Intercept) -0.108623   0.117120  -0.927    0.354    
# td           0.011760   0.001101  10.677  < 2e-16 ***
#   cmp_pct      1.195363   0.209348   5.710 1.85e-08 ***
#   ns_fd_pg    -0.025846   0.005402  -4.784 2.21e-06 ***
#   sack_pct    -1.816037   0.367841  -4.937 1.05e-06 ***
#   ---
#   Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
# 
# Residual standard error: 0.1817 on 548 degrees of freedom
# Multiple R-squared:  0.3833,	Adjusted R-squared:  0.3788 
# F-statistic: 85.15 on 4 and 548 DF,  p-value: < 2.2e-16

## treat collinearity

cor4 <- passer_data %>% 
  select(win_pct, td , cmp_pct , ns_fd_pg , sack_pct) %>% 
  cor() 

View(cor4)

# cor4: r = .70 b/t ns_fd_pg and td; dropped ns_fd_pg

#### Model iteration #5: ####

lm_qb_win_pct = lm(data = passer_data
                   ,win_pct ~ td + cmp_pct + sack_pct
                   ,method = 'qr')
summary(lm_qb_win_pct)

# Call:
#   lm(formula = win_pct ~ td + cmp_pct + sack_pct, data = passer_data, 
#      method = "qr")
# 
# Residuals:
#   Min      1Q  Median      3Q     Max 
# -0.3773 -0.1261  0.0024  0.1246  0.6199 
# 
# Coefficients:
#   Estimate Std. Error t value Pr(>|t|)    
# (Intercept) -0.1285156  0.1193564  -1.077 0.282070    
# td           0.0091293  0.0009732   9.380  < 2e-16 ***
#   cmp_pct      0.8617391  0.2012892   4.281 2.19e-05 ***
#   sack_pct    -1.3784238  0.3633206  -3.794 0.000165 ***
#   ---
#   Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
# 
# Residual standard error: 0.1853 on 549 degrees of freedom
# Multiple R-squared:  0.3576,	Adjusted R-squared:  0.354 
# F-statistic: 101.8 on 3 and 549 DF,  p-value: < 2.2e-16

## treat collinearity << no evidence of collinearity present

cor5 <- passer_data %>% 
  select(win_pct, td , cmp_pct , sack_pct) %>% 
  cor() 

View(cor5)

# cor5: r values < .6 and evidence of collinearity is not present in the model

```

```{r}

fncModelSummary_Univariate(model = lm_adj_net_ypa)
fncModelSummary_Univariate(model = lm_adj_ypa)
fncModelSummary_Univariate(model = lm_cmp_pct)
fncModelSummary_Univariate(model = lm_fd_pa)
fncModelSummary_Univariate(model = lm_fd_pg)
fncModelSummary_Univariate(model = lm_adj_ppr)
fncModelSummary_Univariate(model = lm_first_downs)
fncModelSummary_Univariate(model = lm_int)
fncModelSummary_Univariate(model = lm_int_pct)
fncModelSummary_Univariate(model = lm_int_pg)
fncModelSummary_Univariate(model = lm_int_pinc)
fncModelSummary_Univariate(model = lm_net_ypa)
fncModelSummary_Univariate(model = lm_pass_yds)
fncModelSummary_Univariate(model = lm_sack_pct)
fncModelSummary_Univariate(model = lm_sack_yds)
fncModelSummary_Univariate(model = lm_sk)
fncModelSummary_Univariate(model = lm_td)
fncModelSummary_Univariate(model = lm_td_pc)
fncModelSummary_Univariate(model = lm_td_pg)
fncModelSummary_Univariate(model = lm_ypa)
fncModelSummary_Univariate(model = lm_ypc)
fncModelSummary_Univariate(model = lm_td_int_ratio)
fncModelSummary_Univariate(model = lm_ns_fd)
fncModelSummary_Univariate(model = lm_ns_fd_pg)
fncModelSummary_Univariate(model = lm_ns_fd_pa)


univariate_models_smy_app2 = model_summary %>% 
  arrange(model_pval, desc(model_r2))

rm(model_summary)

#### approach #2: models combined comparison ####

univariate_stability_smy_app2 = univariate_models_smy_app2 %>% 
  mutate(model_ivar = gsub("ly_", "", model_ivar)) %>% 
 rename('yoy_stab_model_pval' = 'model_pval'
         ,'yoy_stab_model_r2' = 'model_r2')

mean_model_r2_app2 = mean(univariate_models_smy_app2$model_r2)
mean_yoy_model_r2_app2 = mean(univariate_stability_smy_app2$yoy_stab_model_r2)

## filter out any variables that are not individual stats (adj_ppr, qbr, first_downs (include td's)) ##
combined_univariate_models_app2 = univariate_models_smy_app2 %>% 
  left_join(univariate_stability_smy_app2 %>% select(model_ivar, yoy_stab_model_pval,yoy_stab_model_r2)
            ,by = 'model_ivar')

combined_model_comp_app2 = univariate_models_smy_app2 %>% 
  left_join(univariate_stability_smy_app2 %>% select(model_ivar, yoy_stab_model_pval,yoy_stab_model_r2)
            ,by = 'model_ivar') %>% 
  filter(model_ivar != 'qbr') %>% 
  filter(model_pval < 0.0001 & yoy_stab_model_pval < 0.0001 ) %>% 
  filter(yoy_stab_model_r2 >= mean_yoy_model_r2_app2)

#### Approach #2: Model iteration #1 ####

lm_qb_win_pct_app2 = lm(data = passer_data
                        ,win_pct ~ adj_ppr + td + fd_pa + td_pg + first_downs + pass_yds + ns_fd + cmp_pct +
                          fd_pg + ns_fd_pg + sack_pct
                        ,method = 'qr')
summary(lm_qb_win_pct_app2)
# 
# Call:
#   lm(formula = win_pct ~ adj_ppr + td + fd_pa + td_pg + first_downs + 
#        pass_yds + ns_fd + cmp_pct + fd_pg + ns_fd_pg + sack_pct, 
#      data = passer_data, method = "qr")
# 
# Residuals:
#   Min       1Q   Median       3Q      Max 
# -0.48500 -0.11623  0.00686  0.10980  0.61912 
# 
# Coefficients: (2 not defined because of singularities)
# Estimate Std. Error t value Pr(>|t|)    
# (Intercept) -2.450e-01  1.110e-01  -2.206   0.0278 *  
#   adj_ppr      4.978e+00  3.655e+00   1.362   0.1737    
# td           3.117e-03  5.544e-03   0.562   0.5743    
# fd_pa       -3.112e+00  4.128e+00  -0.754   0.4512    
# td_pg       -8.230e-02  1.563e-01  -0.527   0.5987    
# first_downs -3.380e-04  1.178e-03  -0.287   0.7742    
# pass_yds     7.605e-05  4.717e-05   1.612   0.1075    
# ns_fd               NA         NA      NA       NA    
# cmp_pct      3.778e-01  2.184e-01   1.730   0.0842 .  
# fd_pg       -3.215e-02  1.918e-02  -1.676   0.0943 .  
# ns_fd_pg            NA         NA      NA       NA    
# sack_pct    -2.032e+00  3.481e-01  -5.837 9.13e-09 ***
#   ---
#   Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
# 
# Residual standard error: 0.1697 on 543 degrees of freedom
# Multiple R-squared:  0.467,	Adjusted R-squared:  0.4582 
# F-statistic: 52.87 on 9 and 543 DF,  p-value: < 2.2e-16


## treat collinearity

cor1 <- passer_data %>% 
  select(win_pct , adj_ppr , td , fd_pa , td_pg , first_downs , pass_yds , ns_fd , cmp_pct ,
         fd_pg , ns_fd_pg , sack_pct) %>% 

View(cor1)

# cor1: dropped ns_fd and ns_fd_pg for singularities

#### Approach #2: Model iteration #2 ####

lm_qb_win_pct_app2 = lm(data = passer_data
                        ,win_pct ~ adj_ppr + td + fd_pa + td_pg + first_downs + pass_yds + cmp_pct +
                          fd_pg + sack_pct
                        ,method = 'qr')
summary(lm_qb_win_pct_app2)

# Call:
#   lm(formula = win_pct ~ adj_ppr + td + fd_pa + td_pg + first_downs + 
#        pass_yds + cmp_pct + fd_pg + sack_pct, data = passer_data, 
#      method = "qr")
# 
# Residuals:
#   Min       1Q   Median       3Q      Max 
# -0.48500 -0.11623  0.00686  0.10980  0.61912 
# 
# Coefficients:
#   Estimate Std. Error t value Pr(>|t|)    
# (Intercept) -2.450e-01  1.110e-01  -2.206   0.0278 *  
#   adj_ppr      4.978e+00  3.655e+00   1.362   0.1737    
# td           3.117e-03  5.544e-03   0.562   0.5743    
# fd_pa       -3.112e+00  4.128e+00  -0.754   0.4512    
# td_pg       -8.230e-02  1.563e-01  -0.527   0.5987    
# first_downs -3.380e-04  1.178e-03  -0.287   0.7742    
# pass_yds     7.605e-05  4.717e-05   1.612   0.1075    
# cmp_pct      3.778e-01  2.184e-01   1.730   0.0842 .  
# fd_pg       -3.215e-02  1.918e-02  -1.676   0.0943 .  
# sack_pct    -2.032e+00  3.481e-01  -5.837 9.13e-09 ***
#   ---
#   Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
# 
# Residual standard error: 0.1697 on 543 degrees of freedom
# Multiple R-squared:  0.467,	Adjusted R-squared:  0.4582 
# F-statistic: 52.87 on 9 and 543 DF,  p-value: < 2.2e-16


## treat collinearity

cor2 <- passer_data %>% 
  select(win_pct , adj_ppr , td , fd_pa , td_pg , first_downs , pass_yds , cmp_pct ,
         fd_pg , sack_pct) %>% 
  cor() 

View(cor2)

# cor2: r = .99 b/t pass_yds and first_downs; dropped pass_yds

#### Approach #2: Model iteration #3 ####

library(car)


lm_qb_win_pct_app2 = lm(data = passer_data
                        ,win_pct ~ adj_ppr + td + fd_pa + td_pg + first_downs + cmp_pct +
                          fd_pg + sack_pct
                        ,method = 'qr')
summary(lm_qb_win_pct_app2)

# Call:
#   lm(formula = win_pct ~ adj_ppr + td + fd_pa + td_pg + first_downs + 
#        cmp_pct + fd_pg + sack_pct, data = passer_data, method = "qr")
# 
# Residuals:
#   Min       1Q   Median       3Q      Max 
# -0.49585 -0.11250  0.00716  0.10916  0.61640 
# 
# Coefficients:
#   Estimate Std. Error t value Pr(>|t|)    
# (Intercept) -0.2276569  0.1106844  -2.057   0.0402 *  
#   adj_ppr      5.3095396  3.6543161   1.453   0.1468    
# td           0.0030168  0.0055522   0.543   0.5871    
# fd_pa       -3.6349723  4.1216211  -0.882   0.3782    
# td_pg       -0.0809354  0.1565313  -0.517   0.6053    
# first_downs  0.0012160  0.0006774   1.795   0.0732 .  
# cmp_pct      0.4348873  0.2158111   2.015   0.0444 *  
#   fd_pg       -0.0324389  0.0192122  -1.688   0.0919 .  
# sack_pct    -1.9798979  0.3471212  -5.704 1.93e-08 ***
#   ---
#   Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
# 
# Residual standard error: 0.17 on 544 degrees of freedom
# Multiple R-squared:  0.4645,	Adjusted R-squared:  0.4566 
# F-statistic: 58.98 on 8 and 544 DF,  p-value: < 2.2e-16

## treat collinearity

cor3 <- passer_data %>% 
  select(win_pct , adj_ppr , td , fd_pa , td_pg , first_downs , cmp_pct ,
         fd_pg , sack_pct) %>% 
  cor() 

View(cor3)

# cor3: r = .98 b/t fd_pa and adj_ppr; dropped fd_pa

#### Approach #2: Model iteration #4 ####

lm_qb_win_pct_app2 = lm(data = passer_data
                        ,win_pct ~ adj_ppr + td + td_pg + first_downs + cmp_pct +
                          fd_pg + sack_pct
                        ,method = 'qr')
summary(lm_qb_win_pct_app2)

# Call:
#   lm(formula = win_pct ~ adj_ppr + td + td_pg + first_downs + cmp_pct + 
#        fd_pg + sack_pct, data = passer_data, method = "qr")
# 
# Residuals:
#   Min       1Q   Median       3Q      Max 
# -0.51998 -0.11198  0.00631  0.10815  0.61030 
# 
# Coefficients:
#   Estimate Std. Error t value Pr(>|t|)    
# (Intercept) -0.2329524  0.1104989  -2.108   0.0355 *  
#   adj_ppr      2.0937398  0.2414123   8.673  < 2e-16 ***
#   td           0.0012990  0.0051983   0.250   0.8028    
# td_pg        0.0427637  0.0694782   0.615   0.5385    
# first_downs  0.0014090  0.0006409   2.198   0.0283 *  
#   cmp_pct      0.4265278  0.2155589   1.979   0.0484 *  
#   fd_pg       -0.0472723  0.0092836  -5.092 4.89e-07 ***
#   sack_pct    -1.9766007  0.3470303  -5.696 2.01e-08 ***
#   ---
#   Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
# 
# Residual standard error: 0.1699 on 545 degrees of freedom
# Multiple R-squared:  0.4637,	Adjusted R-squared:  0.4568 
# F-statistic: 67.32 on 7 and 545 DF,  p-value: < 2.2e-16

## treat collinearity

cor4 <- passer_data %>% 
  select(win_pct , adj_ppr , td , td_pg , first_downs , cmp_pct ,fd_pg , sack_pct) %>% 
  cor() 

View(cor4)

# cor4: r = .92 b/t first_downs and td; dropped first_downs

#### Approach #2: Model iteration #5 ####

lm_qb_win_pct_app2 = lm(data = passer_data
                        ,win_pct ~ adj_ppr + td + td_pg + cmp_pct +
                          fd_pg + sack_pct
                        ,method = 'qr')
summary(lm_qb_win_pct_app2)

# Call:
#   lm(formula = win_pct ~ adj_ppr + td + td_pg + cmp_pct + fd_pg + 
#        sack_pct, data = passer_data, method = "qr")
# 
# Residuals:
#   Min       1Q   Median       3Q      Max 
# -0.51368 -0.10777  0.00698  0.11014  0.61665 
# 
# Coefficients:
#   Estimate Std. Error t value Pr(>|t|)    
# (Intercept) -0.236524   0.110874  -2.133   0.0333 *  
#   adj_ppr      2.114240   0.242077   8.734  < 2e-16 ***
#   td           0.012140   0.001650   7.356 7.01e-13 ***
#   td_pg       -0.088461   0.035681  -2.479   0.0135 *  
#   cmp_pct      0.419604   0.216291   1.940   0.0529 .  
# fd_pg       -0.030310   0.005181  -5.850 8.45e-09 ***
#   sack_pct    -2.024786   0.347551  -5.826 9.71e-09 ***
#   ---
#   Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
# 
# Residual standard error: 0.1705 on 546 degrees of freedom
# Multiple R-squared:  0.4589,	Adjusted R-squared:  0.453 
# F-statistic: 77.19 on 6 and 546 DF,  p-value: < 2.2e-16

## treat collinearity

cor5 <- passer_data %>% 
  select(win_pct , adj_ppr , td , td_pg , cmp_pct ,fd_pg , sack_pct) %>% 
  cor() 

View(cor5)

# cor5: r = .90 b/t td_pg and td; dropped td_pg

#### Approach #2: Model iteration #6 ####

lm_qb_win_pct_app2 = lm(data = passer_data
                        ,win_pct ~ adj_ppr + td + cmp_pct +
                          fd_pg + sack_pct
                        ,method = 'qr')
summary(lm_qb_win_pct_app2)

# Call:
#   lm(formula = win_pct ~ adj_ppr + td + cmp_pct + fd_pg + sack_pct, 
#      data = passer_data, method = "qr")
# 
# Residuals:
#   Min       1Q   Median       3Q      Max 
# -0.50086 -0.11160  0.00599  0.11720  0.57219 
# 
# Coefficients:
#   Estimate Std. Error t value Pr(>|t|)    
# (Intercept) -0.221998   0.111239  -1.996   0.0465 *  
#   adj_ppr      1.880318   0.223980   8.395 4.01e-16 ***
#   td           0.009351   0.001213   7.707 6.10e-14 ***
#   cmp_pct      0.483568   0.215755   2.241   0.0254 *  
#   fd_pg       -0.033768   0.005013  -6.736 4.12e-11 ***
#   sack_pct    -1.958607   0.348151  -5.626 2.95e-08 ***
#   ---
#   Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
# 
# Residual standard error: 0.1713 on 547 degrees of freedom
# Multiple R-squared:  0.4529,	Adjusted R-squared:  0.4479 
# F-statistic: 90.55 on 5 and 547 DF,  p-value: < 2.2e-16

## treat collinearity

cor6 <- passer_data %>% 
  select(win_pct , adj_ppr , td , cmp_pct ,fd_pg , sack_pct) %>% 
  cor() 

View(cor6)

# cor6: r = .78 b/t fd_pg and td; dropped fd_pg

#### Approach #2: Model iteration #7 ####

lm_qb_win_pct_app2 = lm(data = passer_data
                        ,win_pct ~ adj_ppr + td + cmp_pct + sack_pct
                        ,method = 'qr')
summary(lm_qb_win_pct_app2)

# Call:
#   lm(formula = win_pct ~ adj_ppr + td + cmp_pct + sack_pct, data = passer_data, 
#      method = "qr")
# 
# Residuals:
#   Min       1Q   Median       3Q      Max 
# -0.48167 -0.12184  0.01105  0.12260  0.48956 
# 
# Coefficients:
#   Estimate Std. Error t value Pr(>|t|)    
# (Intercept) -0.227508   0.115652  -1.967 0.049667 *  
#   adj_ppr      1.541833   0.226937   6.794 2.85e-11 ***
#   td           0.005279   0.001094   4.826 1.80e-06 ***
#   cmp_pct      0.166146   0.218906   0.759 0.448188    
# sack_pct    -1.342960   0.349279  -3.845 0.000135 ***
#   ---
#   Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
# 
# Residual standard error: 0.1781 on 548 degrees of freedom
# Multiple R-squared:  0.4075,	Adjusted R-squared:  0.4031 
# F-statistic: 94.21 on 4 and 548 DF,  p-value: < 2.2e-16

## treat collinearity

cor7 <- passer_data %>% 
  select(win_pct , adj_ppr , td , cmp_pct , sack_pct) %>% 
  cor() 

View(cor7)

# cor7: r = .71 b/t adj_ppr and td; dropped td

#### Approach #2: Model iteration #8 ####

lm_qb_win_pct_app2 = lm(data = passer_data
                        ,win_pct ~ adj_ppr + cmp_pct + sack_pct
                        ,method = 'qr')
summary(lm_qb_win_pct_app2)

# Call:
#   lm(formula = win_pct ~ adj_ppr + cmp_pct + sack_pct, data = passer_data, 
#      method = "qr")
# 
# Residuals:
#   Min       1Q   Median       3Q      Max 
# -0.57902 -0.11871  0.01608  0.12724  0.42877 
# 
# Coefficients:
#   Estimate Std. Error t value Pr(>|t|)    
# (Intercept)  -0.4226     0.1105  -3.823 0.000147 ***
#   adj_ppr       2.1093     0.1980  10.653  < 2e-16 ***
#   cmp_pct       0.3272     0.2207   1.482 0.138823    
# sack_pct     -1.8017     0.3429  -5.255 2.12e-07 ***
#   ---
#   Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
# 
# Residual standard error: 0.1817 on 549 degrees of freedom
# Multiple R-squared:  0.3823,	Adjusted R-squared:  0.3789 
# F-statistic: 113.2 on 3 and 549 DF,  p-value: < 2.2e-16

## treat collinearity

cor8 <- passer_data %>% 
  select(win_pct , adj_ppr , cmp_pct , sack_pct) %>% 
  cor() 

View(cor8)

# cor8: r = .67 b/t adj_ppr and cmp_pct; dropped cmp_pct

#### Approach #2: Model iteration #9 ####

lm_qb_win_pct_app2 = lm(data = passer_data
                        ,win_pct ~ adj_ppr + sack_pct
                        ,method = 'qr')
summary(lm_qb_win_pct_app2)

# Call:
#   lm(formula = win_pct ~ adj_ppr + sack_pct, data = passer_data, 
#      method = "qr")
# 
# Residuals:
#   Min       1Q   Median       3Q      Max 
# -0.59532 -0.11850  0.01928  0.12545  0.43338 
# 
# Coefficients:
#   Estimate Std. Error t value Pr(>|t|)    
# (Intercept) -0.29325    0.06797  -4.314 1.90e-05 ***
#   adj_ppr      2.29914    0.15119  15.207  < 2e-16 ***
#   sack_pct    -1.82920    0.34272  -5.337 1.38e-07 ***
#   ---
#   Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
# 
# Residual standard error: 0.1819 on 550 degrees of freedom
# Multiple R-squared:  0.3798,	Adjusted R-squared:  0.3775 
# F-statistic: 168.4 on 2 and 550 DF,  p-value: < 2.2e-16


## no evidence of multicollinearity present!


#### predict xWinPct ###

## test data ##

qbs_2019 = passer_data_pfr %>% 
  mutate(adj_ppr = (first_downs+td)/att) %>% 
  filter(szn == 2019) %>% 
  mutate(xWinPct = predict(lm_qb_win_pct, newdata = ., type = 'response')
         ,xWinPct2 = predict(lm_qb_win_pct_app2, newdata = ., type = 'response')) %>% 
  select(player, tm, qbrec, td, cmp_pct, sack_pct,adj_ppr, win_pct, xWinPct, xWinPct2) %>% 
  mutate(WPOE = win_pct - xWinPct
         ,xWinPct_rank = rank(-xWinPct, ties.method = 'min', na.last = 'keep')
         ,WPOE2 = win_pct - xWinPct2
         ,xWinPct_rank2 = rank(-xWinPct2, ties.method = 'min', na.last = 'keep')) %>% 
  arrange(xWinPct_rank)

test_data = qbs_2019 %>% 
  mutate(abs_dev = abs(win_pct - xWinPct)
         ,abs_dev2 = abs(win_pct - xWinPct2))

MAD = mean(test_data$abs_dev)
MAD_games = MAD*16

MAD2 = mean(test_data$abs_dev2)
MAD_games2 = MAD2*16

#### advanced stats ####

## join football outsiders data ##
adv_passer_data = passer_data %>% 
  mutate(player_abbv = paste0(substr(player, 1,1),".",substr(player, regexpr(' ', player)+1, nchar(player)))) %>% 
  left_join(passer_data_fo %>% select(player, szn, dyar, dvoa, voa), by = c('player_abbv'='player', 'szn'='szn')) %>% 
  mutate(dyar = as.numeric(sub(",","",dyar)))

lm_qbr = lm(data = adv_passer_data
            ,win_pct ~ qbr
            ,method = 'qr')
summary(lm_qbr)

lm_dvoa = lm(data = adv_passer_data
             ,win_pct ~ dvoa
             ,method = 'qr')
summary(lm_dvoa)

lm_voa = lm(data = adv_passer_data
            ,win_pct ~ voa
            ,method = 'qr')
summary(lm_voa)

lm_dyar = lm(data = adv_passer_data
             ,win_pct ~ dyar
             ,method = 'qr')
summary(lm_dyar)

adv_passer_data = adv_passer_data %>% 
  left_join(passer_data_nflscrapr %>% select(passer_player_name, szn, epa_db, cpoe)
            , by = c('player_abbv'='passer_player_name', 'szn'='szn')) %>% 
  rename('brownalytics_cpoe' = 'cpoe')

lm_epa_db = lm(data = adv_passer_data
               ,win_pct ~ epa_db
               ,method = 'qr')
summary(lm_epa_db)

lm_brownalytics_cpoe = lm(data = adv_passer_data
                          ,win_pct ~ brownalytics_cpoe
                          ,method = 'qr')
summary(lm_brownalytics_cpoe)

adv_passer_data = adv_passer_data %>% 
  left_join(passer_data_airyards %>% select(full_name, szn, cpoe)
            , by = c('player'='full_name', 'szn'='szn')) %>% 
  rename('airyards_cpoe' = 'cpoe')

lm_airyards_cpoe = lm(data = adv_passer_data
                      ,win_pct ~ airyards_cpoe
                      ,method = 'qr')
summary(lm_airyards_cpoe)

fncModelSummary_Univariate(model = lm_dvoa)
fncModelSummary_Univariate(model = lm_dyar)
fncModelSummary_Univariate(model = lm_voa)
fncModelSummary_Univariate(model = lm_epa_db)
fncModelSummary_Univariate(model = lm_brownalytics_cpoe)
fncModelSummary_Univariate(model = lm_airyards_cpoe)
fncModelSummary_Univariate(model = lm_qbr)

adv_model_summary = model_summary
rm(model_summary)

#### advanced model stability ####
adv_passer_stability = adv_passer_data %>%
  select(player, szn, qbr) %>%
  arrange(player, szn) %>%
  group_by(player) %>%
  mutate(ly_qbr = lag(qbr)) %>%
  ungroup()

lm_qbr_stab = lm(data = adv_passer_stability
                 ,qbr ~ ly_qbr
                 ,method = 'qr')
summary(lm_qbr_stab)

adv_passer_stability = adv_passer_data %>%
  select(player, szn, dvoa) %>%
  arrange(player, szn) %>%
  group_by(player) %>%
  mutate(ly_dvoa = lag(dvoa)) %>%
  ungroup()

lm_dvoa_stab = lm(data = adv_passer_stability
                  ,dvoa ~ ly_dvoa
                  ,method = 'qr')
summary(lm_dvoa_stab)

adv_passer_stability = adv_passer_data %>%
  select(player, szn, dyar) %>%
  arrange(player, szn) %>%
  group_by(player) %>%
  mutate(ly_dyar = lag(dyar)) %>%
  ungroup()

lm_dyar_stab = lm(data = adv_passer_stability
                  ,dyar ~ ly_dyar
                  ,method = 'qr')
summary(lm_dyar_stab)

adv_passer_stability = adv_passer_data %>%
  select(player, szn, voa) %>%
  arrange(player, szn) %>%
  group_by(player) %>%
  mutate(ly_voa = lag(voa)) %>%
  ungroup()

lm_voa_stab = lm(data = adv_passer_stability
                 ,voa ~ ly_voa
                 ,method = 'qr')
summary(lm_voa_stab)

adv_passer_stability = adv_passer_data %>%
  select(player, szn, epa_db) %>%
  arrange(player, szn) %>%
  group_by(player) %>%
  mutate(ly_epa_db = lag(epa_db)) %>%
  ungroup()

lm_epa_db_stab = lm(data = adv_passer_stability
                    ,epa_db ~ ly_epa_db
                    ,method = 'qr')
summary(lm_epa_db_stab)

adv_passer_stability = adv_passer_data %>%
  select(player, szn, brownalytics_cpoe) %>%
  arrange(player, szn) %>%
  group_by(player) %>%
  mutate(ly_brownalytics_cpoe = lag(brownalytics_cpoe)) %>%
  ungroup()

lm_brownalytics_cpoe_stab = lm(data = adv_passer_stability
                               ,brownalytics_cpoe ~ ly_brownalytics_cpoe
                               ,method = 'qr')
summary(lm_brownalytics_cpoe_stab)

adv_passer_stability = adv_passer_data %>%
  select(player, szn, airyards_cpoe) %>%
  arrange(player, szn) %>%
  group_by(player) %>%
  mutate(ly_airyards_cpoe = lag(airyards_cpoe)) %>%
  ungroup()

lm_airyards_cpoe_stab = lm(data = adv_passer_stability
                           ,airyards_cpoe ~ ly_airyards_cpoe
                           ,method = 'qr')
summary(lm_airyards_cpoe_stab)

fncModelSummary_Univariate(model = lm_dvoa_stab)
fncModelSummary_Univariate(model = lm_dyar_stab)
fncModelSummary_Univariate(model = lm_voa_stab)
fncModelSummary_Univariate(model = lm_epa_db_stab)
fncModelSummary_Univariate(model = lm_brownalytics_cpoe_stab)
fncModelSummary_Univariate(model = lm_airyards_cpoe_stab)
fncModelSummary_Univariate(model = lm_qbr_stab)

adv_stability_smy = model_summary
rm(model_summary)

#### combine model outputs ####

adv_stability_smy = adv_stability_smy %>% 
  mutate(model_ivar = gsub("ly_", "", model_ivar)) %>% 
  rename('yoy_stab_model_pval' = 'model_pval'
         ,'yoy_stab_model_r2' = 'model_r2')

adv_combined_model_comp = adv_model_summary %>% 
  left_join(adv_stability_smy %>% select(model_ivar, yoy_stab_model_pval,yoy_stab_model_r2)
            ,by = 'model_ivar') %>% 
  arrange(desc(model_r2), desc(yoy_stab_model_r2))

#### add fd+td-sack% to advanced table ####

rm(model_summary)

fncModelSummary_Univariate(model = lm_qb_win_pct)
fncModelSummary_Univariate(model = lm_qb_win_pct_app2)


tmp_model_smy = model_summary %>% 
  mutate(model_ivar = ifelse(model_ivar == 'td', 'td+cmp_pct-sack_pct', 
                             ifelse(model_ivar == 'adj_ppr', 'adj_ppr-sack_pct',NA)))
rm(model_summary)

adv_passer_stability = adv_passer_data %>%
  mutate(xWinPct = predict(lm_qb_win_pct, newdata =., type = 'response')) %>%
  select(player, szn, xWinPct) %>%
  arrange(player, szn) %>%
  group_by(player) %>%
  mutate(ly_xWinPct = lag(xWinPct)) %>%
  ungroup()

lm_xWinPct_stab = lm(data = adv_passer_stability
                     ,xWinPct ~ ly_xWinPct
                     ,method = 'qr')
summary(lm_xWinPct_stab)


adv_passer_stability = adv_passer_data %>%
  mutate(xWinPct2 = predict(lm_qb_win_pct_app2, newdata =., type = 'response')) %>%
  select(player, szn, xWinPct2) %>%
  arrange(player, szn) %>%
  group_by(player) %>%
  mutate(ly_xWinPct2 = lag(xWinPct2)) %>%
  ungroup()

lm_xWinPct2_stab = lm(data = adv_passer_stability
                      ,xWinPct2 ~ ly_xWinPct2
                      ,method = 'qr')
summary(lm_xWinPct2_stab)

fncModelSummary_Univariate(model = lm_xWinPct_stab)
fncModelSummary_Univariate(model = lm_xWinPct2_stab)

tmp_adv_model_smy = model_summary %>% 
  mutate(model_ivar = ifelse(model_ivar == 'ly_xWinPct', 'conventional_stats', 
                             ifelse(model_ivar == 'ly_xWinPct2', 'adj_stats',NA))) %>% 
  rename('yoy_stab_model_pval' = 'model_pval'
         ,'yoy_stab_model_r2' = 'model_r2')

tmp_model_comp = tmp_model_smy %>% 
  left_join(tmp_adv_model_smy %>% select(model_ivar, yoy_stab_model_pval,yoy_stab_model_r2)
            ,by = 'model_ivar') 

adv_combined_model_comp = adv_combined_model_comp %>% 
  full_join(tmp_model_comp
            , by = c("model_name", "model_ivar", "model_pval", "model_r2", "yoy_stab_model_pval", "yoy_stab_model_r2")) %>% 
  arrange(desc(model_r2)) 


# lm_cpoe = lm(data = adv_passer_data, airyards_cpoe ~ brownalytics_cpoe, method = 'qr')

#### predict xWinPct from advanced stats ####

qbs_2019_adv = qbs_2019 %>% 
  mutate(szn = 2019
         ,player_abbv = paste0(substr(player, 1,1),".",substr(player, regexpr(' ', player)+1, nchar(player)))) %>% 
  left_join(passer_data_fo %>% select(player, szn, dyar, dvoa, voa), by = c('player_abbv'='player', 'szn'='szn')) %>% 
  mutate(dyar = as.numeric(dyar)) %>% 
  left_join(passer_data_nflscrapr %>% select(passer_player_name, szn, epa_db, cpoe)
            , by = c('player_abbv'='passer_player_name', 'szn'='szn')) %>% 
  rename('brownalytics_cpoe' = 'cpoe') %>% 
  left_join(passer_data_airyards %>% select(full_name, szn, cpoe)
            , by = c('player'='full_name', 'szn'='szn')) %>% 
  left_join(passer_data_pfr %>% select(player, szn, qbr)
            , by = c('player'='player', 'szn'='szn')) %>% 
  rename('airyards_cpoe' = 'cpoe'
         ,'xWinPct_ba' = 'xWinPct'
         , 'xWinPct_ba2' = 'xWinPct2') %>% 
  mutate(xWinPct_epa_db = predict(lm_epa_db, newdata = ., type = 'response')
         ,xWinPct_qbr = predict(lm_qbr, newdata = ., type = 'response')
         ,xWinPct_dvoa = predict(lm_dvoa, newdata = ., type = 'response')
         ,xWinPct_voa = predict(lm_voa, newdata = ., type = 'response')
         ,xWinPct_dyar = predict(lm_dyar, newdata = ., type = 'response')
         ,xWinPct_brownalytics_cpoe = predict(lm_brownalytics_cpoe, newdata = ., type = 'response')
         ,xWinPct_airyards_cpoe = predict(lm_airyards_cpoe, newdata = ., type = 'response'))

lm_xwin_epa = lm(data = qbs_2019_adv
                 ,xWinPct_ba ~ xWinPct_epa_db
                 ,method = 'qr')
summary(lm_xwin_epa)

lm_xwin_epa2 = lm(data = qbs_2019_adv
                  ,xWinPct_ba2 ~ xWinPct_epa_db
                  ,method = 'qr')
summary(lm_xwin_epa2)


lm_xwin_dvoa = lm(data = qbs_2019_adv
                  ,xWinPct_ba ~ xWinPct_dvoa
                  ,method = 'qr')
summary(lm_xwin_dvoa)

lm_xwin_dvoa2 = lm(data = qbs_2019_adv
                   ,xWinPct_ba2 ~ xWinPct_dvoa
                   ,method = 'qr')
summary(lm_xwin_dvoa2)


lm_xwin_voa = lm(data = qbs_2019_adv
                 ,xWinPct_ba ~ xWinPct_voa
                 ,method = 'qr')
summary(lm_xwin_voa)

lm_xwin_voa2 = lm(data = qbs_2019_adv
                  ,xWinPct_ba2 ~ xWinPct_voa
                  ,method = 'qr')
summary(lm_xwin_voa2)


lm_xwin_dyar = lm(data = qbs_2019_adv
                  ,xWinPct_ba ~ xWinPct_dyar
                  ,method = 'qr')
summary(lm_xwin_dyar)

lm_xwin_dyar2 = lm(data = qbs_2019_adv
                   ,xWinPct_ba2 ~ xWinPct_dyar
                   ,method = 'qr')
summary(lm_xwin_dyar2)


lm_xwin_brownalytics_cpoe = lm(data = qbs_2019_adv
                               ,xWinPct_ba ~ xWinPct_brownalytics_cpoe
                               ,method = 'qr')
summary(lm_xwin_brownalytics_cpoe)

lm_xwin_brownalytics_cpoe2 = lm(data = qbs_2019_adv
                                ,xWinPct_ba2 ~ xWinPct_brownalytics_cpoe
                                ,method = 'qr')
summary(lm_xwin_brownalytics_cpoe2)

lm_xwin_airyards_cpoe = lm(data = qbs_2019_adv
                           ,xWinPct_ba ~ xWinPct_airyards_cpoe
                           ,method = 'qr')
summary(lm_xwin_airyards_cpoe)

lm_xwin_airyards_cpoe2 = lm(data = qbs_2019_adv
                            ,xWinPct_ba2 ~ xWinPct_airyards_cpoe
                            ,method = 'qr')
summary(lm_xwin_airyards_cpoe2)


lm_xwin_qbr = lm(data = qbs_2019_adv
                 ,xWinPct_ba ~ xWinPct_qbr 
                 ,method = 'qr')
summary(lm_xwin_qbr)

lm_xwin_qbr2 = lm(data = qbs_2019_adv
                  ,xWinPct_ba2 ~ xWinPct_qbr 
                  ,method = 'qr')
summary(lm_xwin_qbr2)


rm(model_summary)

fncModelSummary_Univariate(model = lm_xwin_epa)
fncModelSummary_Univariate(model = lm_xwin_dvoa)
fncModelSummary_Univariate(model = lm_xwin_voa)
fncModelSummary_Univariate(model = lm_xwin_dyar)
fncModelSummary_Univariate(model = lm_xwin_qbr)
fncModelSummary_Univariate(model = lm_xwin_airyards_cpoe)
fncModelSummary_Univariate(model = lm_xwin_brownalytics_cpoe)
fncModelSummary_Univariate(model = lm_xwin_epa2)
fncModelSummary_Univariate(model = lm_xwin_dvoa2)
fncModelSummary_Univariate(model = lm_xwin_voa2)
fncModelSummary_Univariate(model = lm_xwin_dyar2)
fncModelSummary_Univariate(model = lm_xwin_qbr2)
fncModelSummary_Univariate(model = lm_xwin_airyards_cpoe2)
fncModelSummary_Univariate(model = lm_xwin_brownalytics_cpoe2)


xWinPct_models_comp = model_summary
rm(model_summary)

xWinPct_models_comp1 = xWinPct_models_comp %>% 
  mutate(model_tested = ifelse(substr(model_name, nchar(model_name), nchar(model_name))=='2'
                               , 'Adjusted Conventional Stats'
                               , 'Conventional Stats')) %>% 
  filter(model_tested == 'Conventional Stats')

xWinPct_models_comp2 = xWinPct_models_comp %>% 
  mutate(model_tested = ifelse(substr(model_name, nchar(model_name), nchar(model_name))=='2'
                               , 'Adjusted Conventional Stats'
                               , 'Conventional Stats')) %>% 
  filter(model_tested == 'Adjusted Conventional Stats') %>% 
  rename('adj_model_pval' = 'model_pval'
         ,'adj_model_r2' = 'model_r2')

xWinPct_models_comp = xWinPct_models_comp1 %>% 
  left_join(xWinPct_models_comp2 %>% select(model_ivar, adj_model_pval, adj_model_r2), by = 'model_ivar') %>% 
  mutate(model_name = NULL
         ,model_tested = NULL
         ,model_ivar = sub('xWinPct_','', model_ivar))



```

